@startuml
start
    : receive the figure feature data;
    :call the math function to different construction methods;
    :generate the points to figure choosen;
if (have problems?) then (yes)
    :show error message;
else (no)
    :send the generated points to robot module;
    :interact the trajectory profile module\n to draw the choosen figure on the screen;
endif
stop
@enduml