@startuml
start
if (start button is active) then (yes)
    :show the initial messages;
    :show the goemetric figure menu;
    :input the selection menu;
    if () then (user cancelled the operation)
        :ending process;
    else (user choosen an option)
        :configure the figure feature;
        :show the choosen figure features;
        :interacts of trajectory generator;
        :generation the points;
        if (have the problem?) then (yes)
            :show error message;
        else (no)
            :show the thank message;
        endif
        :ending process;
    endif
else (no)
    :turn-off system;
    :ending process;
endif
stop
@enduml