@startuml
Class Screen{
    + Screen(): construtor
    + showMessage():
   
}
Class RTGS{
    - onOffRCS: false
    - startRCS: false
    + RTGS(): construtor
    + readFigureOption()
    + sendFigureOption()
    + showMessage()
    
}
Class RTGSMain(){
    + RTGSMain(): construtor
    + activateRTGS()
    + inicializeSystem()
    + showMessage()
}
Class ModbusNetInterface{
    - slaveNumber
    - deviceAddres
    - functionCode
    - operationData: 
    - errorCheck: 0x00
    - isProblem: false
    + execute()
    + char: requestMasterToSlave()
    + char: receiveSlaveToMaster()
}
Class Controller{
    - controllerType
    - proportionalConst
    - settlingTime
    - overshootPercent
    - damperFactor
    - naturalFreq
    - risingtTime
    - isRobotOk
    + Controller(): construtor
    + processingControl ()
    + execute(controlparameters)
    + sendAngularPosition()
    + sendModbusNetData()
    + readControlParameters()
    + processingRobotDataToControl()
    + turnOffSystem();
    + showMessage()
}
abstract class Transaction{
    + execute()
}
class TrajectoryProfile{
    + execute()
    + drawFigure()
    + showMessage()
}
class TrajectoryGenerator{
    -  profileType
    -  pointControlNumber
    -  curvature
    + TrajectoryGenerator():construtor
    + saveProfileOption()
    + processingProfileOption()
    + chargeTrajectoryParameters()
    + buildTrajectoryProfile()
    + execute(pontos)
    + showMessage()
}
class EmargencyStop{
    - keyState: false
    + EmargencyStop(): construtor
    + sendEmergencyStop()
     
}
class RobotModel{
    - dOFNumber
    - Ai
    - Thetai
    - Alphai
    + RobotModel(): construtor
    + solveDKinematic()
    + solveIKinematic()
    + sendIKparametrs()
    + buildModbusControlPath()
    + sendDKParameters()
    + requestMasterToSlave()
    + receiveSlaveToMaster()
}
class Keypad{
    - option:  0
    + Keypad(): construtor
    + getInput()
    + sendInput()
}
@enduml