@startuml
abstract class "Transaction"
RTGS *---EmergencyStop
RTGS *---Screen
RTGS *---Mouse
RTGS *---Controller
RTGS *--- RobotModel
RTGS ---> "Transaction" : excute
"Transaction" <|-- MakeTrajectoryProfile
"Transaction" <|-- MakeModbusNetInterface
"Transaction" ---> RobotModel : acess/modify the robot params
"Transaction" ---> Screen : draw the figure

@enduml