@startuml
actor User as Foo1
Foo1 -> EmergencyStop: press button
boundary RTGSMain as Foo2
control RTGS as Foo3
loop while the Emergency condition is active
    EmergencyStop ->Controller: sendEmergencyStop()
    Controller ->Foo3: turn-Off()
    Controller -> Screen: showMessage()
    Screen -->Foo1:show Alert message
end 
@enduml