@startuml
control RTGS as Foo3
Foo3 -> Transactions: sendFigureOption()
Transactions -> MakeTrajectoryProfile:execute()
MakeTrajectoryProfile -> RobotModel:execute(points)
 loop while the built figure has concluded by robot model
       RobotModel ->Controller:sendIKparameters()
       Controller -> MakeModbusNetInterface:requestMasterToSlave()
       MakeModbusNetInterface -->Controller:receiveSlaveToMaster()
       Controller --> RobotModel: sendAngularPosition()
       RobotModel ->Controller:sendDKParams()
       Controller ->MakeModbusNetInterface: requestMasterToSlave()
    end
RobotModel -->Foo3: figure drawn by robot
@enduml