@startuml
actor User as Foo1
Foo1 -> Mouse: press button
boundary RTGSMain as Foo2
Mouse -> Foo2: sendImput()
control RTGS as Foo3
Foo2 -> Foo3: Processing option
Foo3 -> Screen: showMessage()
Foo3 -> Transaction: sendFigureOption()
Transaction -> MakeTrajectoryProfile: execute()
 loop each trajetory strategy: draw and enable the robot 
    MakeTrajectoryProfile ->RobotModel: execute(points)
    loop while the built figure by robot model
       RobotModel ->Controller:sendIKparameters()
       Controller -> MakeModbusNetInterface:execute(controlParams)
       MakeModbusNetInterface -->Controller:receiveSlaveToMaster()
       Controller --> RobotModel: sendAngularPosition()
       RobotModel ->Controller:sendDKParams()
       Controller ->MakeModbusNetInterface: execute(controlPoints)
    end

end
RobotModel -->Screen: figure drawn by robot
Screen --> Foo1: drawn figures
@enduml