
@startuml
control RTGS as Foo3
Foo3 -> Screen: showMessage()
Screen --> Foo3: show the option choosen
Foo3 -> TrajectoryGenerator: sendFigureOption()
group sd Build the figures [Transactions]
    TrajectoryGenerator -> TrajectoryProfile:execute()
    TrajectoryProfile -->Screen: draw figures
end
Screen --> Foo3: drawn figures
@enduml